import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pact - Make Informed Decisions",
  description: "Generated by create next app",
  creator: "Xooniverse",
  authors: [
    {
      name: "Xooniverse",
      url: "https://xooniverse.com"
    }
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
